// Auto-generated by OpenLane
module compute_core(
`ifdef USE_POWER_PINS
  inout VPWR,
  inout VGND,
`endif
  input clk,
  input rst,
  input en,
  input valid_in,
  input[7:0] activation,
  input[7:0] weight,
  output[31:0] acc_out,
  output valid_out,
  output done
);
endmodule
